### ISSUE TITLE
Display out put not correctly with Extension MessagePack

### ISSUE THREAD

**Issue by measproem** [ocelot-inc/ocelotgui-tarantool#1]
Some space contain field type Extension MessagePack like `datetime` not display
https://www.tarantool.io/en/doc/latest/dev_guide/internals/msgpack_extensions/

**Comment by pgulutzan** [comment]
Yes, ocelotgui does not properly support the datetime data type which was added in Tarantool version 2.10.0. There is a plan to add support for it in ocelotgui version 2.2.

I apologize for being slow to notice this. To ensure that a comment is seen more quickly, it might be better to send a private note to the email address mentioned in the readme file.

**Comment by measproem** [comment]
Thank I used your tool will send some feedback more

**Comment by pgulutzan** [comment]
@measproem The bug is fixed in our source code, the patch was added today to
https://github.com/ocelot-inc/ocelotgui 
If you clone from there and build from the source, you can read datetimes.
Can you please send the feedback that you mentioned?

**Comment by measproem** [comment]
Thank! but I  used [Window](https://github.com/ocelot-inc/ocelotgui#Appendix-4) not able build from source yet, can you uplaod or any url link I could easy download test and give feedback, 
I personaly forked [Rust crate](https://github.com/measproem/alopecosa) make change to support UUID, DateTime, Decimal may help idea for your future version.

**Comment by pgulutzan** [comment]
I can make a special executable for Windows, I'll let you know if/when it's done. The version that you have already should work with UUID and decimal. Only Datetime was difficult because handling nanoseconds and named time zones and negative years required understanding some undocumented quirks. I've only tested with Tarantool 2.11 but doubt Tarantool 3.0 differs.

**Comment by pgulutzan** [comment]
@measproem: On
https://github.com/ocelot-inc/ocelotgui/releases/tag/2.1.0
is a new temporary file named ocelotgui.exe.
Click to download it and display rows with datetimes.
I'm interested in any feedback.

**Comment by measproem** [comment]
Confirmed UUID, Datetime, Decimal are  working thank you,
![image](https://github.com/ocelot-inc/ocelotgui-tarantool/assets/12493849/55ada864-885e-49f6-a8e2-242b41023106)
![image](https://github.com/ocelot-inc/ocelotgui-tarantool/assets/12493849/9c20e22d-bc9b-481e-a06c-2087a81bc8ed)

**Comment by pgulutzan** [comment]
Good. I'll delete the temporary ocelotgui.exe in a few days.
I'd be grateful if you send more feedback before the next version is released in a few weeks.
Also I'd be grateful if you would consider going to https://github.com/ocelot-inc/ocelotgui-tarantool/ and clicking the "Star" button, and/or telling your friends about the product.

**Comment by measproem** [comment]
Some more feedback on the ocelotgui user interface - it's functional but could be easier to use:

1. Mouse selection makes it really hard to copy output data after executing an SQL query.
2. The ability to resize columns would be helpful.
3. Pagination is needed - with 100 rows it's okay, but with 1000 rows it's hard to scroll through them all.
4. The SQL query editor should not clear the query after executing it, because developers often need to iteratively modify queries until they get the expected output.
5. Inline editing/deleting and saving of data is needed.

**Comment by pgulutzan** [comment]
These are good feature requests but maybe you haven't noticed that, partially, there are answers already.
1. In Settings | History Widget change Max Row Count to 5.   After that the history widget will include an ASCII-delimited copy of the first 5 rows when you SELECT.  You'll probably find that's easier to copy. Or you an pick File|Export from the menu.
2. Sometimes You can resize cells by going to Settings | Grid Widget and changing font size or cell width (though this works only when the cell contents are smaller), and you might find that saying  SELECT column_name AS really_really_really_long_name ... causes cells to be wider, and you can drag the output i.e. put your cursor over the line that separates columns and press   and move the cursor right, the cell will grow temporarily.
3. I'm not sure what this means, but if the desire is to see the row number: If you put the mouse over a row in the display, a temporary popup appears that shows the row number. If the desire is to scroll more than one row at a time, I think that dragging the slider on the scroll bar does that well even when there are thousands of rows.
4. Type control-P and you'll see the last query you executed. Type control-P twice and you'll see the second-last query you executed.
5. Put your cursor over an updatable column in the grid display. Click (the colour will probably change to show that cell is in focus.)  Now type a letter, e.g. 'd'. You'll see that the statement widget contains a generated UPDATE statement.  You'll probably need to edit the UPDATE statement because we don't do a good job of finding the  best keys for the WHERE clause, but I guess that's what you mean by inline editing.

**Comment by measproem** [comment]
Thank you, I misread the document. Let me check it more carefully.

**Comment by pgulutzan** [comment]
Today I pushed ocelotgui version 2.2.0. It contains the fix. So I am closing this bug report. Thanks!
